// Code generated by protoc-gen-go. DO NOT EDIT.
// source: facade.proto

package facade

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Mode int32

const (
	Mode_GRID  Mode = 0
	Mode_DRAFT Mode = 16
)

var Mode_name = map[int32]string{
	0:  "GRID",
	16: "DRAFT",
}
var Mode_value = map[string]int32{
	"GRID":  0,
	"DRAFT": 16,
}

func (x Mode) String() string {
	return proto.EnumName(Mode_name, int32(x))
}
func (Mode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_facade_60556de91d7f36cd, []int{0}
}

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_facade_60556de91d7f36cd, []int{0}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type Text struct {
	Text                 []byte   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Text) Reset()         { *m = Text{} }
func (m *Text) String() string { return proto.CompactTextString(m) }
func (*Text) ProtoMessage()    {}
func (*Text) Descriptor() ([]byte, []int) {
	return fileDescriptor_facade_60556de91d7f36cd, []int{1}
}
func (m *Text) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Text.Unmarshal(m, b)
}
func (m *Text) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Text.Marshal(b, m, deterministic)
}
func (dst *Text) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Text.Merge(dst, src)
}
func (m *Text) XXX_Size() int {
	return xxx_messageInfo_Text.Size(m)
}
func (m *Text) XXX_DiscardUnknown() {
	xxx_messageInfo_Text.DiscardUnknown(m)
}

var xxx_messageInfo_Text proto.InternalMessageInfo

func (m *Text) GetText() []byte {
	if m != nil {
		return m.Text
	}
	return nil
}

type Config struct {
	Debug                bool        `protobuf:"varint,1,opt,name=Debug,proto3" json:"Debug,omitempty"`
	Mode                 Mode        `protobuf:"varint,2,opt,name=Mode,proto3,enum=facade.Mode" json:"Mode,omitempty"`
	Grid                 *GridConfig `protobuf:"bytes,3,opt,name=Grid,proto3" json:"Grid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_facade_60556de91d7f36cd, []int{2}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (dst *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(dst, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetDebug() bool {
	if m != nil {
		return m.Debug
	}
	return false
}

func (m *Config) GetMode() Mode {
	if m != nil {
		return m.Mode
	}
	return Mode_GRID
}

func (m *Config) GetGrid() *GridConfig {
	if m != nil {
		return m.Grid
	}
	return nil
}

type GridConfig struct {
	Width                int32    `protobuf:"varint,1,opt,name=Width,proto3" json:"Width,omitempty"`
	Height               int32    `protobuf:"varint,2,opt,name=Height,proto3" json:"Height,omitempty"`
	Downward             bool     `protobuf:"varint,3,opt,name=Downward,proto3" json:"Downward,omitempty"`
	Speed                float32  `protobuf:"fixed32,4,opt,name=Speed,proto3" json:"Speed,omitempty"`
	Buffer               int32    `protobuf:"varint,5,opt,name=Buffer,proto3" json:"Buffer,omitempty"`
	Terminal             bool     `protobuf:"varint,6,opt,name=Terminal,proto3" json:"Terminal,omitempty"`
	Vert                 string   `protobuf:"bytes,7,opt,name=Vert,proto3" json:"Vert,omitempty"`
	Frag                 string   `protobuf:"bytes,8,opt,name=Frag,proto3" json:"Frag,omitempty"`
	Fill                 string   `protobuf:"bytes,16,opt,name=Fill,proto3" json:"Fill,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GridConfig) Reset()         { *m = GridConfig{} }
func (m *GridConfig) String() string { return proto.CompactTextString(m) }
func (*GridConfig) ProtoMessage()    {}
func (*GridConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_facade_60556de91d7f36cd, []int{3}
}
func (m *GridConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GridConfig.Unmarshal(m, b)
}
func (m *GridConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GridConfig.Marshal(b, m, deterministic)
}
func (dst *GridConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GridConfig.Merge(dst, src)
}
func (m *GridConfig) XXX_Size() int {
	return xxx_messageInfo_GridConfig.Size(m)
}
func (m *GridConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_GridConfig.DiscardUnknown(m)
}

var xxx_messageInfo_GridConfig proto.InternalMessageInfo

func (m *GridConfig) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *GridConfig) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *GridConfig) GetDownward() bool {
	if m != nil {
		return m.Downward
	}
	return false
}

func (m *GridConfig) GetSpeed() float32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *GridConfig) GetBuffer() int32 {
	if m != nil {
		return m.Buffer
	}
	return 0
}

func (m *GridConfig) GetTerminal() bool {
	if m != nil {
		return m.Terminal
	}
	return false
}

func (m *GridConfig) GetVert() string {
	if m != nil {
		return m.Vert
	}
	return ""
}

func (m *GridConfig) GetFrag() string {
	if m != nil {
		return m.Frag
	}
	return ""
}

func (m *GridConfig) GetFill() string {
	if m != nil {
		return m.Fill
	}
	return ""
}

func init() {
	proto.RegisterType((*Response)(nil), "facade.Response")
	proto.RegisterType((*Text)(nil), "facade.Text")
	proto.RegisterType((*Config)(nil), "facade.Config")
	proto.RegisterType((*GridConfig)(nil), "facade.GridConfig")
	proto.RegisterEnum("facade.Mode", Mode_name, Mode_value)
}

func init() { proto.RegisterFile("facade.proto", fileDescriptor_facade_60556de91d7f36cd) }

var fileDescriptor_facade_60556de91d7f36cd = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x41, 0x6b, 0xe3, 0x30,
	0x10, 0x85, 0x57, 0x59, 0xdb, 0xeb, 0xcc, 0x86, 0x60, 0x86, 0x65, 0x11, 0xe9, 0xc5, 0xf8, 0x50,
	0x44, 0xa1, 0x39, 0xa4, 0xbf, 0xa0, 0xad, 0x49, 0xda, 0x43, 0xa1, 0xa8, 0xa1, 0x3d, 0x3b, 0xf5,
	0xd8, 0x11, 0xb8, 0xb6, 0x51, 0x14, 0x92, 0x1f, 0xdb, 0x1f, 0x53, 0x24, 0xc5, 0xe9, 0xa1, 0xb7,
	0xf9, 0xde, 0x0c, 0xef, 0xc1, 0x1b, 0x98, 0x54, 0xc5, 0x7b, 0x51, 0xd2, 0xbc, 0xd7, 0x9d, 0xe9,
	0x30, 0xf2, 0x94, 0x01, 0xc4, 0x92, 0x76, 0x7d, 0xd7, 0xee, 0x28, 0x9b, 0x41, 0xb0, 0xa6, 0xa3,
	0x41, 0x84, 0xc0, 0xd0, 0xd1, 0x70, 0x96, 0x32, 0x31, 0x91, 0x6e, 0xce, 0xb6, 0x10, 0xdd, 0x77,
	0x6d, 0xa5, 0x6a, 0xfc, 0x07, 0x61, 0x4e, 0x9b, 0x7d, 0xed, 0xd6, 0xb1, 0xf4, 0x80, 0x29, 0x04,
	0x4f, 0x5d, 0x49, 0x7c, 0x94, 0x32, 0x31, 0x5d, 0x4c, 0xe6, 0xa7, 0x30, 0xab, 0x49, 0xb7, 0xc1,
	0x4b, 0x08, 0x56, 0x5a, 0x95, 0xfc, 0x77, 0xca, 0xc4, 0xdf, 0x05, 0x0e, 0x17, 0x56, 0xf3, 0xce,
	0xd2, 0xed, 0xb3, 0x4f, 0x06, 0xf0, 0x2d, 0xda, 0xb8, 0x37, 0x55, 0x9a, 0xad, 0x8b, 0x0b, 0xa5,
	0x07, 0xfc, 0x0f, 0xd1, 0x03, 0xa9, 0x7a, 0x6b, 0x5c, 0x60, 0x28, 0x4f, 0x84, 0x33, 0x88, 0xf3,
	0xee, 0xd0, 0x1e, 0x0a, 0xed, 0x83, 0x62, 0x79, 0x66, 0xeb, 0xf4, 0xd2, 0x13, 0x95, 0x3c, 0x48,
	0x99, 0x18, 0x49, 0x0f, 0xd6, 0xe9, 0x6e, 0x5f, 0x55, 0xa4, 0x79, 0xe8, 0x9d, 0x3c, 0x59, 0xa7,
	0x35, 0xe9, 0x0f, 0xd5, 0x16, 0x0d, 0x8f, 0xbc, 0xd3, 0xc0, 0xb6, 0xa0, 0x57, 0xd2, 0x86, 0xff,
	0x49, 0x99, 0x18, 0x4b, 0x37, 0x5b, 0x6d, 0xa9, 0x8b, 0x9a, 0xc7, 0x5e, 0xb3, 0xb3, 0xd3, 0x54,
	0xd3, 0xf0, 0xe4, 0xa4, 0xa9, 0xa6, 0xb9, 0xba, 0xf0, 0x45, 0x61, 0x0c, 0xc1, 0x4a, 0x3e, 0xe6,
	0xc9, 0x2f, 0x1c, 0x43, 0x98, 0xcb, 0xdb, 0xe5, 0x3a, 0x49, 0x16, 0x05, 0x44, 0x4b, 0x57, 0x0b,
	0x5e, 0xc3, 0xd8, 0x17, 0xb0, 0xd7, 0x84, 0xd3, 0xa1, 0x2c, 0x2f, 0xcd, 0x92, 0x81, 0x87, 0xd7,
	0xa1, 0x80, 0xe0, 0x59, 0xf5, 0x84, 0xe7, 0xe2, 0xed, 0x23, 0x7f, 0xde, 0x09, 0xb6, 0x89, 0xdc,
	0xff, 0x6f, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x59, 0x4c, 0xc8, 0x0f, 0x02, 0x00, 0x00,
}
