// Code generated by protoc-gen-go. DO NOT EDIT.
// source: facade.proto

package facade

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Mode int32

const (
	Mode_TERM  Mode = 0
	Mode_LINE  Mode = 1
	Mode_TAGS  Mode = 2
	Mode_DRAFT Mode = 16
)

var Mode_name = map[int32]string{
	0:  "TERM",
	1:  "LINE",
	2:  "TAGS",
	16: "DRAFT",
}

var Mode_value = map[string]int32{
	"TERM":  0,
	"LINE":  1,
	"TAGS":  2,
	"DRAFT": 16,
}

func (x Mode) String() string {
	return proto.EnumName(Mode_name, int32(x))
}

func (Mode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5478f20a07eaa28e, []int{0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_5478f20a07eaa28e, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Status struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	Info                 string   `protobuf:"bytes,3,opt,name=Info,proto3" json:"Info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_5478f20a07eaa28e, []int{1}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Status) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Status) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type RawText struct {
	Raw                  []byte   `protobuf:"bytes,1,opt,name=Raw,proto3" json:"Raw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawText) Reset()         { *m = RawText{} }
func (m *RawText) String() string { return proto.CompactTextString(m) }
func (*RawText) ProtoMessage()    {}
func (*RawText) Descriptor() ([]byte, []int) {
	return fileDescriptor_5478f20a07eaa28e, []int{2}
}

func (m *RawText) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawText.Unmarshal(m, b)
}
func (m *RawText) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawText.Marshal(b, m, deterministic)
}
func (m *RawText) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawText.Merge(m, src)
}
func (m *RawText) XXX_Size() int {
	return xxx_messageInfo_RawText.Size(m)
}
func (m *RawText) XXX_DiscardUnknown() {
	xxx_messageInfo_RawText.DiscardUnknown(m)
}

var xxx_messageInfo_RawText proto.InternalMessageInfo

func (m *RawText) GetRaw() []byte {
	if m != nil {
		return m.Raw
	}
	return nil
}

type Config struct {
	SetDebug             bool          `protobuf:"varint,1,opt,name=SetDebug,proto3" json:"SetDebug,omitempty"`
	Debug                bool          `protobuf:"varint,2,opt,name=Debug,proto3" json:"Debug,omitempty"`
	SetMode              bool          `protobuf:"varint,3,opt,name=SetMode,proto3" json:"SetMode,omitempty"`
	Mode                 Mode          `protobuf:"varint,4,opt,name=Mode,proto3,enum=facade.Mode" json:"Mode,omitempty"`
	Font                 *FontConfig   `protobuf:"bytes,5,opt,name=Font,proto3" json:"Font,omitempty"`
	Camera               *CameraConfig `protobuf:"bytes,6,opt,name=Camera,proto3" json:"Camera,omitempty"`
	Mask                 *MaskConfig   `protobuf:"bytes,7,opt,name=Mask,proto3" json:"Mask,omitempty"`
	Terminal             *TermConfig   `protobuf:"bytes,13,opt,name=Terminal,proto3" json:"Terminal,omitempty"`
	Lines                *LineConfig   `protobuf:"bytes,14,opt,name=Lines,proto3" json:"Lines,omitempty"`
	Tags                 *TagConfig    `protobuf:"bytes,15,opt,name=Tags,proto3" json:"Tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_5478f20a07eaa28e, []int{3}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetSetDebug() bool {
	if m != nil {
		return m.SetDebug
	}
	return false
}

func (m *Config) GetDebug() bool {
	if m != nil {
		return m.Debug
	}
	return false
}

func (m *Config) GetSetMode() bool {
	if m != nil {
		return m.SetMode
	}
	return false
}

func (m *Config) GetMode() Mode {
	if m != nil {
		return m.Mode
	}
	return Mode_TERM
}

func (m *Config) GetFont() *FontConfig {
	if m != nil {
		return m.Font
	}
	return nil
}

func (m *Config) GetCamera() *CameraConfig {
	if m != nil {
		return m.Camera
	}
	return nil
}

func (m *Config) GetMask() *MaskConfig {
	if m != nil {
		return m.Mask
	}
	return nil
}

func (m *Config) GetTerminal() *TermConfig {
	if m != nil {
		return m.Terminal
	}
	return nil
}

func (m *Config) GetLines() *LineConfig {
	if m != nil {
		return m.Lines
	}
	return nil
}

func (m *Config) GetTags() *TagConfig {
	if m != nil {
		return m.Tags
	}
	return nil
}

type FontConfig struct {
	SetName              bool     `protobuf:"varint,1,opt,name=SetName,proto3" json:"SetName,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FontConfig) Reset()         { *m = FontConfig{} }
func (m *FontConfig) String() string { return proto.CompactTextString(m) }
func (*FontConfig) ProtoMessage()    {}
func (*FontConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5478f20a07eaa28e, []int{4}
}

func (m *FontConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FontConfig.Unmarshal(m, b)
}
func (m *FontConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FontConfig.Marshal(b, m, deterministic)
}
func (m *FontConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FontConfig.Merge(m, src)
}
func (m *FontConfig) XXX_Size() int {
	return xxx_messageInfo_FontConfig.Size(m)
}
func (m *FontConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_FontConfig.DiscardUnknown(m)
}

var xxx_messageInfo_FontConfig proto.InternalMessageInfo

func (m *FontConfig) GetSetName() bool {
	if m != nil {
		return m.SetName
	}
	return false
}

func (m *FontConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CameraConfig struct {
	SetZoom              bool     `protobuf:"varint,1,opt,name=SetZoom,proto3" json:"SetZoom,omitempty"`
	Zoom                 float64  `protobuf:"fixed64,2,opt,name=Zoom,proto3" json:"Zoom,omitempty"`
	SetIsometric         bool     `protobuf:"varint,3,opt,name=SetIsometric,proto3" json:"SetIsometric,omitempty"`
	Isometric            bool     `protobuf:"varint,4,opt,name=Isometric,proto3" json:"Isometric,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CameraConfig) Reset()         { *m = CameraConfig{} }
func (m *CameraConfig) String() string { return proto.CompactTextString(m) }
func (*CameraConfig) ProtoMessage()    {}
func (*CameraConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5478f20a07eaa28e, []int{5}
}

func (m *CameraConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CameraConfig.Unmarshal(m, b)
}
func (m *CameraConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CameraConfig.Marshal(b, m, deterministic)
}
func (m *CameraConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CameraConfig.Merge(m, src)
}
func (m *CameraConfig) XXX_Size() int {
	return xxx_messageInfo_CameraConfig.Size(m)
}
func (m *CameraConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_CameraConfig.DiscardUnknown(m)
}

var xxx_messageInfo_CameraConfig proto.InternalMessageInfo

func (m *CameraConfig) GetSetZoom() bool {
	if m != nil {
		return m.SetZoom
	}
	return false
}

func (m *CameraConfig) GetZoom() float64 {
	if m != nil {
		return m.Zoom
	}
	return 0
}

func (m *CameraConfig) GetSetIsometric() bool {
	if m != nil {
		return m.SetIsometric
	}
	return false
}

func (m *CameraConfig) GetIsometric() bool {
	if m != nil {
		return m.Isometric
	}
	return false
}

type MaskConfig struct {
	SetName              bool     `protobuf:"varint,1,opt,name=SetName,proto3" json:"SetName,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaskConfig) Reset()         { *m = MaskConfig{} }
func (m *MaskConfig) String() string { return proto.CompactTextString(m) }
func (*MaskConfig) ProtoMessage()    {}
func (*MaskConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5478f20a07eaa28e, []int{6}
}

func (m *MaskConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaskConfig.Unmarshal(m, b)
}
func (m *MaskConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaskConfig.Marshal(b, m, deterministic)
}
func (m *MaskConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaskConfig.Merge(m, src)
}
func (m *MaskConfig) XXX_Size() int {
	return xxx_messageInfo_MaskConfig.Size(m)
}
func (m *MaskConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_MaskConfig.DiscardUnknown(m)
}

var xxx_messageInfo_MaskConfig proto.InternalMessageInfo

func (m *MaskConfig) GetSetName() bool {
	if m != nil {
		return m.SetName
	}
	return false
}

func (m *MaskConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ShaderConfig struct {
	SetVert              bool     `protobuf:"varint,1,opt,name=SetVert,proto3" json:"SetVert,omitempty"`
	Vert                 string   `protobuf:"bytes,2,opt,name=Vert,proto3" json:"Vert,omitempty"`
	SetFrag              bool     `protobuf:"varint,3,opt,name=SetFrag,proto3" json:"SetFrag,omitempty"`
	Frag                 string   `protobuf:"bytes,4,opt,name=Frag,proto3" json:"Frag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShaderConfig) Reset()         { *m = ShaderConfig{} }
func (m *ShaderConfig) String() string { return proto.CompactTextString(m) }
func (*ShaderConfig) ProtoMessage()    {}
func (*ShaderConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5478f20a07eaa28e, []int{7}
}

func (m *ShaderConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShaderConfig.Unmarshal(m, b)
}
func (m *ShaderConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShaderConfig.Marshal(b, m, deterministic)
}
func (m *ShaderConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShaderConfig.Merge(m, src)
}
func (m *ShaderConfig) XXX_Size() int {
	return xxx_messageInfo_ShaderConfig.Size(m)
}
func (m *ShaderConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ShaderConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ShaderConfig proto.InternalMessageInfo

func (m *ShaderConfig) GetSetVert() bool {
	if m != nil {
		return m.SetVert
	}
	return false
}

func (m *ShaderConfig) GetVert() string {
	if m != nil {
		return m.Vert
	}
	return ""
}

func (m *ShaderConfig) GetSetFrag() bool {
	if m != nil {
		return m.SetFrag
	}
	return false
}

func (m *ShaderConfig) GetFrag() string {
	if m != nil {
		return m.Frag
	}
	return ""
}

type TermConfig struct {
	Shader               *ShaderConfig `protobuf:"bytes,1,opt,name=Shader,proto3" json:"Shader,omitempty"`
	Grid                 *GridConfig   `protobuf:"bytes,2,opt,name=Grid,proto3" json:"Grid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TermConfig) Reset()         { *m = TermConfig{} }
func (m *TermConfig) String() string { return proto.CompactTextString(m) }
func (*TermConfig) ProtoMessage()    {}
func (*TermConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5478f20a07eaa28e, []int{8}
}

func (m *TermConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TermConfig.Unmarshal(m, b)
}
func (m *TermConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TermConfig.Marshal(b, m, deterministic)
}
func (m *TermConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TermConfig.Merge(m, src)
}
func (m *TermConfig) XXX_Size() int {
	return xxx_messageInfo_TermConfig.Size(m)
}
func (m *TermConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TermConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TermConfig proto.InternalMessageInfo

func (m *TermConfig) GetShader() *ShaderConfig {
	if m != nil {
		return m.Shader
	}
	return nil
}

func (m *TermConfig) GetGrid() *GridConfig {
	if m != nil {
		return m.Grid
	}
	return nil
}

type LineConfig struct {
	Shader               *ShaderConfig `protobuf:"bytes,1,opt,name=Shader,proto3" json:"Shader,omitempty"`
	Grid                 *GridConfig   `protobuf:"bytes,2,opt,name=Grid,proto3" json:"Grid,omitempty"`
	SetDownward          bool          `protobuf:"varint,3,opt,name=SetDownward,proto3" json:"SetDownward,omitempty"`
	Downward             bool          `protobuf:"varint,4,opt,name=Downward,proto3" json:"Downward,omitempty"`
	SetSpeed             bool          `protobuf:"varint,5,opt,name=SetSpeed,proto3" json:"SetSpeed,omitempty"`
	Speed                float64       `protobuf:"fixed64,6,opt,name=Speed,proto3" json:"Speed,omitempty"`
	SetFixed             bool          `protobuf:"varint,7,opt,name=SetFixed,proto3" json:"SetFixed,omitempty"`
	Fixed                bool          `protobuf:"varint,8,opt,name=Fixed,proto3" json:"Fixed,omitempty"`
	SetDrop              bool          `protobuf:"varint,9,opt,name=SetDrop,proto3" json:"SetDrop,omitempty"`
	Drop                 bool          `protobuf:"varint,10,opt,name=Drop,proto3" json:"Drop,omitempty"`
	SetStop              bool          `protobuf:"varint,11,opt,name=SetStop,proto3" json:"SetStop,omitempty"`
	Stop                 bool          `protobuf:"varint,12,opt,name=Stop,proto3" json:"Stop,omitempty"`
	SetBuffer            bool          `protobuf:"varint,13,opt,name=SetBuffer,proto3" json:"SetBuffer,omitempty"`
	Buffer               uint64        `protobuf:"varint,14,opt,name=Buffer,proto3" json:"Buffer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LineConfig) Reset()         { *m = LineConfig{} }
func (m *LineConfig) String() string { return proto.CompactTextString(m) }
func (*LineConfig) ProtoMessage()    {}
func (*LineConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5478f20a07eaa28e, []int{9}
}

func (m *LineConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LineConfig.Unmarshal(m, b)
}
func (m *LineConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LineConfig.Marshal(b, m, deterministic)
}
func (m *LineConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LineConfig.Merge(m, src)
}
func (m *LineConfig) XXX_Size() int {
	return xxx_messageInfo_LineConfig.Size(m)
}
func (m *LineConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_LineConfig.DiscardUnknown(m)
}

var xxx_messageInfo_LineConfig proto.InternalMessageInfo

func (m *LineConfig) GetShader() *ShaderConfig {
	if m != nil {
		return m.Shader
	}
	return nil
}

func (m *LineConfig) GetGrid() *GridConfig {
	if m != nil {
		return m.Grid
	}
	return nil
}

func (m *LineConfig) GetSetDownward() bool {
	if m != nil {
		return m.SetDownward
	}
	return false
}

func (m *LineConfig) GetDownward() bool {
	if m != nil {
		return m.Downward
	}
	return false
}

func (m *LineConfig) GetSetSpeed() bool {
	if m != nil {
		return m.SetSpeed
	}
	return false
}

func (m *LineConfig) GetSpeed() float64 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *LineConfig) GetSetFixed() bool {
	if m != nil {
		return m.SetFixed
	}
	return false
}

func (m *LineConfig) GetFixed() bool {
	if m != nil {
		return m.Fixed
	}
	return false
}

func (m *LineConfig) GetSetDrop() bool {
	if m != nil {
		return m.SetDrop
	}
	return false
}

func (m *LineConfig) GetDrop() bool {
	if m != nil {
		return m.Drop
	}
	return false
}

func (m *LineConfig) GetSetStop() bool {
	if m != nil {
		return m.SetStop
	}
	return false
}

func (m *LineConfig) GetStop() bool {
	if m != nil {
		return m.Stop
	}
	return false
}

func (m *LineConfig) GetSetBuffer() bool {
	if m != nil {
		return m.SetBuffer
	}
	return false
}

func (m *LineConfig) GetBuffer() uint64 {
	if m != nil {
		return m.Buffer
	}
	return 0
}

type GridConfig struct {
	SetWidth             bool     `protobuf:"varint,1,opt,name=SetWidth,proto3" json:"SetWidth,omitempty"`
	Width                uint64   `protobuf:"varint,2,opt,name=Width,proto3" json:"Width,omitempty"`
	SetHeight            bool     `protobuf:"varint,3,opt,name=SetHeight,proto3" json:"SetHeight,omitempty"`
	Height               uint64   `protobuf:"varint,4,opt,name=Height,proto3" json:"Height,omitempty"`
	SetFill              bool     `protobuf:"varint,5,opt,name=SetFill,proto3" json:"SetFill,omitempty"`
	Fill                 string   `protobuf:"bytes,6,opt,name=Fill,proto3" json:"Fill,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GridConfig) Reset()         { *m = GridConfig{} }
func (m *GridConfig) String() string { return proto.CompactTextString(m) }
func (*GridConfig) ProtoMessage()    {}
func (*GridConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5478f20a07eaa28e, []int{10}
}

func (m *GridConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GridConfig.Unmarshal(m, b)
}
func (m *GridConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GridConfig.Marshal(b, m, deterministic)
}
func (m *GridConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GridConfig.Merge(m, src)
}
func (m *GridConfig) XXX_Size() int {
	return xxx_messageInfo_GridConfig.Size(m)
}
func (m *GridConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_GridConfig.DiscardUnknown(m)
}

var xxx_messageInfo_GridConfig proto.InternalMessageInfo

func (m *GridConfig) GetSetWidth() bool {
	if m != nil {
		return m.SetWidth
	}
	return false
}

func (m *GridConfig) GetWidth() uint64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *GridConfig) GetSetHeight() bool {
	if m != nil {
		return m.SetHeight
	}
	return false
}

func (m *GridConfig) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *GridConfig) GetSetFill() bool {
	if m != nil {
		return m.SetFill
	}
	return false
}

func (m *GridConfig) GetFill() string {
	if m != nil {
		return m.Fill
	}
	return ""
}

type TagConfig struct {
	Shader               *ShaderConfig `protobuf:"bytes,1,opt,name=Shader,proto3" json:"Shader,omitempty"`
	SetFill              bool          `protobuf:"varint,3,opt,name=SetFill,proto3" json:"SetFill,omitempty"`
	Fill                 string        `protobuf:"bytes,4,opt,name=Fill,proto3" json:"Fill,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TagConfig) Reset()         { *m = TagConfig{} }
func (m *TagConfig) String() string { return proto.CompactTextString(m) }
func (*TagConfig) ProtoMessage()    {}
func (*TagConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5478f20a07eaa28e, []int{11}
}

func (m *TagConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagConfig.Unmarshal(m, b)
}
func (m *TagConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagConfig.Marshal(b, m, deterministic)
}
func (m *TagConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagConfig.Merge(m, src)
}
func (m *TagConfig) XXX_Size() int {
	return xxx_messageInfo_TagConfig.Size(m)
}
func (m *TagConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TagConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TagConfig proto.InternalMessageInfo

func (m *TagConfig) GetShader() *ShaderConfig {
	if m != nil {
		return m.Shader
	}
	return nil
}

func (m *TagConfig) GetSetFill() bool {
	if m != nil {
		return m.SetFill
	}
	return false
}

func (m *TagConfig) GetFill() string {
	if m != nil {
		return m.Fill
	}
	return ""
}

func init() {
	proto.RegisterEnum("facade.Mode", Mode_name, Mode_value)
	proto.RegisterType((*Empty)(nil), "facade.Empty")
	proto.RegisterType((*Status)(nil), "facade.Status")
	proto.RegisterType((*RawText)(nil), "facade.RawText")
	proto.RegisterType((*Config)(nil), "facade.Config")
	proto.RegisterType((*FontConfig)(nil), "facade.FontConfig")
	proto.RegisterType((*CameraConfig)(nil), "facade.CameraConfig")
	proto.RegisterType((*MaskConfig)(nil), "facade.MaskConfig")
	proto.RegisterType((*ShaderConfig)(nil), "facade.ShaderConfig")
	proto.RegisterType((*TermConfig)(nil), "facade.TermConfig")
	proto.RegisterType((*LineConfig)(nil), "facade.LineConfig")
	proto.RegisterType((*GridConfig)(nil), "facade.GridConfig")
	proto.RegisterType((*TagConfig)(nil), "facade.TagConfig")
}

func init() { proto.RegisterFile("facade.proto", fileDescriptor_5478f20a07eaa28e) }

var fileDescriptor_5478f20a07eaa28e = []byte{
	// 766 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xcd, 0x6e, 0x1a, 0x49,
	0x10, 0xf6, 0xc0, 0x30, 0x40, 0x19, 0xdb, 0x6c, 0xcb, 0x5a, 0x8d, 0xbc, 0x3e, 0xa0, 0x91, 0x76,
	0x85, 0x56, 0x09, 0x91, 0x9c, 0x5b, 0x6e, 0x8e, 0x01, 0xc7, 0x92, 0x6d, 0x29, 0x33, 0x28, 0x91,
	0x72, 0x6b, 0x33, 0x0d, 0x9e, 0x04, 0x18, 0xd4, 0xd3, 0x08, 0xfb, 0x92, 0x77, 0xc8, 0x25, 0x0f,
	0x90, 0x77, 0xcc, 0x3d, 0xaa, 0xaa, 0x9e, 0x1f, 0xe4, 0x5c, 0x7c, 0xc8, 0xad, 0xbe, 0xaf, 0xbe,
	0xea, 0xea, 0xee, 0xaa, 0xea, 0x86, 0xce, 0x4c, 0x4e, 0x65, 0xac, 0x06, 0x6b, 0x9d, 0x9a, 0x54,
	0x78, 0x8c, 0x82, 0x26, 0x34, 0x46, 0xcb, 0xb5, 0x79, 0x0c, 0xae, 0xc1, 0x8b, 0x8c, 0x34, 0x9b,
	0x4c, 0xf8, 0xd0, 0x8c, 0x36, 0xd3, 0xa9, 0xca, 0x32, 0xdf, 0xe9, 0x39, 0xfd, 0x56, 0x98, 0x43,
	0x71, 0x0c, 0x8d, 0x91, 0xd6, 0xa9, 0xf6, 0x6b, 0x3d, 0xa7, 0xdf, 0x0e, 0x19, 0x08, 0x01, 0xee,
	0xd5, 0x6a, 0x96, 0xfa, 0x75, 0x22, 0xc9, 0x0e, 0xfe, 0x81, 0x66, 0x28, 0xb7, 0x13, 0xf5, 0x60,
	0x44, 0x17, 0xea, 0xa1, 0xdc, 0xd2, 0x52, 0x9d, 0x10, 0xcd, 0xe0, 0x67, 0x0d, 0xbc, 0x8b, 0x74,
	0x35, 0x4b, 0xe6, 0xe2, 0x04, 0x5a, 0x91, 0x32, 0x43, 0x75, 0xb7, 0x99, 0xdb, 0x64, 0x05, 0xc6,
	0x6c, 0xec, 0xa8, 0x91, 0x83, 0x01, 0xed, 0x4e, 0x99, 0x9b, 0x34, 0x56, 0x94, 0x10, 0x77, 0xc7,
	0x50, 0xf4, 0xc0, 0x25, 0xda, 0xed, 0x39, 0xfd, 0xc3, 0xb3, 0xce, 0xc0, 0x9e, 0x17, 0xb9, 0x90,
	0x3c, 0xe2, 0x3f, 0x70, 0xc7, 0xe9, 0xca, 0xf8, 0x8d, 0x9e, 0xd3, 0xdf, 0x3f, 0x13, 0xb9, 0x02,
	0x39, 0xde, 0x4f, 0x48, 0x7e, 0xf1, 0x02, 0xbc, 0x0b, 0xb9, 0x54, 0x5a, 0xfa, 0x1e, 0x29, 0x8f,
	0x73, 0x25, 0xb3, 0x56, 0x6b, 0x35, 0xb8, 0xea, 0x8d, 0xcc, 0xbe, 0xf8, 0xcd, 0xdd, 0x55, 0x91,
	0xcb, 0x57, 0x45, 0x5b, 0x0c, 0xa0, 0x35, 0x51, 0x7a, 0x99, 0xac, 0xe4, 0xc2, 0x3f, 0xd8, 0xd5,
	0x22, 0x6f, 0xb5, 0x85, 0x46, 0xf4, 0xa1, 0x71, 0x9d, 0xac, 0x54, 0xe6, 0x1f, 0xee, 0x8a, 0x91,
	0xb4, 0x62, 0x16, 0x88, 0x7f, 0xc1, 0x9d, 0xc8, 0x79, 0xe6, 0x1f, 0x91, 0xf0, 0xaf, 0x62, 0x55,
	0x39, 0xcf, 0x37, 0x80, 0xee, 0xe0, 0x0d, 0x40, 0x79, 0x54, 0x7b, 0x91, 0xb7, 0x72, 0xa9, 0x8a,
	0x32, 0x33, 0xc4, 0x82, 0x12, 0xcd, 0x55, 0x26, 0x3b, 0xf8, 0x0a, 0x9d, 0xea, 0xe1, 0x6d, 0xf4,
	0xa7, 0x34, 0x5d, 0x56, 0xa2, 0x11, 0x62, 0x34, 0xd1, 0x18, 0xed, 0x84, 0x64, 0x8b, 0x00, 0x3a,
	0x91, 0x32, 0x57, 0x59, 0xba, 0x54, 0x46, 0x27, 0x53, 0x5b, 0xb9, 0x1d, 0x4e, 0x9c, 0x42, 0xbb,
	0x14, 0xb8, 0x24, 0x28, 0x09, 0xdc, 0x7b, 0x79, 0xa1, 0xcf, 0xdc, 0xfb, 0x67, 0xe8, 0x44, 0xf7,
	0x32, 0x56, 0x7a, 0x27, 0xfa, 0x83, 0xd2, 0xa6, 0x12, 0x8d, 0x10, 0xa3, 0x89, 0xb6, 0xd1, 0xc4,
	0xb1, 0x7a, 0xac, 0xe5, 0xbc, 0xd2, 0x70, 0x08, 0x51, 0x4d, 0xb4, 0xcb, 0x6a, 0xb4, 0x83, 0x3b,
	0x80, 0xb2, 0x98, 0xd8, 0x48, 0x9c, 0x99, 0x12, 0x55, 0x1a, 0xa9, 0xba, 0x9f, 0xd0, 0x6a, 0xb0,
	0x91, 0x2e, 0x75, 0x12, 0x53, 0xf6, 0x4a, 0xbd, 0x91, 0xcb, 0xeb, 0x88, 0x76, 0xf0, 0xbd, 0x0e,
	0x50, 0x36, 0xc1, 0x9f, 0x49, 0x22, 0x7a, 0xb0, 0x8f, 0x93, 0x98, 0x6e, 0x57, 0x5b, 0xa9, 0x63,
	0x7b, 0xf4, 0x2a, 0x85, 0xb3, 0x5b, 0xb8, 0xb9, 0x5e, 0xad, 0xaa, 0x2f, 0x52, 0x26, 0x5a, 0x2b,
	0x15, 0xd3, 0xb4, 0xf1, 0x5c, 0x13, 0xc6, 0xb9, 0x66, 0x87, 0x47, 0x1d, 0xc2, 0xc0, 0x46, 0x8c,
	0x93, 0x07, 0x15, 0xd3, 0x24, 0x71, 0x04, 0x61, 0x8c, 0x60, 0x47, 0x8b, 0x5f, 0x02, 0x66, 0xb9,
	0x30, 0x43, 0x9d, 0xae, 0xfd, 0x76, 0x51, 0x18, 0x84, 0x58, 0x18, 0xa2, 0x81, 0x68, 0xb2, 0xad,
	0x3a, 0x32, 0xe9, 0xda, 0xdf, 0x2f, 0xd4, 0x08, 0x51, 0x4d, 0x74, 0x87, 0xd5, 0xc4, 0x9d, 0x42,
	0x3b, 0x52, 0xe6, 0xed, 0x66, 0x36, 0x53, 0x9a, 0x86, 0xb5, 0x15, 0x96, 0x84, 0xf8, 0x1b, 0x3c,
	0xeb, 0xc2, 0xd1, 0x74, 0x43, 0x8b, 0x82, 0x1f, 0x0e, 0x40, 0x79, 0x91, 0xf6, 0x48, 0x1f, 0x93,
	0xd8, 0xdc, 0x57, 0x1e, 0x37, 0xc2, 0x78, 0x24, 0x76, 0xd4, 0x68, 0x05, 0x06, 0x36, 0xed, 0x3b,
	0x95, 0xcc, 0xef, 0x8d, 0xbd, 0xf2, 0x92, 0xc0, 0xb4, 0xd6, 0xe5, 0x72, 0x5a, 0xcb, 0xdb, 0x0e,
	0x4d, 0x16, 0x0b, 0x7b, 0xd7, 0x39, 0xa4, 0x0e, 0x45, 0xda, 0xb3, 0x1d, 0x9a, 0x2c, 0x16, 0xc1,
	0x1c, 0xda, 0xc5, 0xc3, 0xf0, 0xcc, 0xde, 0xa9, 0x24, 0xaa, 0xff, 0x3e, 0x91, 0x5b, 0x26, 0xfa,
	0xff, 0x15, 0xbf, 0xc7, 0xa2, 0x05, 0xee, 0x64, 0x14, 0xde, 0x74, 0xf7, 0xd0, 0xba, 0xbe, 0xba,
	0x1d, 0x75, 0x1d, 0xe2, 0xce, 0x2f, 0xa3, 0x6e, 0x4d, 0xb4, 0xa1, 0x31, 0x0c, 0xcf, 0xc7, 0x93,
	0x6e, 0xf7, 0xec, 0x9b, 0x03, 0xde, 0x98, 0xd2, 0x8b, 0x97, 0xd0, 0xe6, 0xdc, 0x1b, 0xad, 0xc4,
	0x61, 0xf1, 0xfc, 0x12, 0x75, 0x52, 0x60, 0xfe, 0xb0, 0x82, 0x3d, 0x31, 0x80, 0xe6, 0x30, 0xc9,
	0xd6, 0x0b, 0xf9, 0x28, 0x8e, 0x72, 0xa7, 0xfd, 0x7f, 0x9e, 0xaa, 0xfb, 0x0e, 0x3e, 0xad, 0xef,
	0x37, 0x4a, 0x3f, 0x8a, 0x83, 0xdc, 0x49, 0x9f, 0xe0, 0x53, 0xed, 0x9d, 0x47, 0xdf, 0xe5, 0xeb,
	0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfb, 0xe7, 0x31, 0x3b, 0x3e, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FacadeClient is the client API for Facade service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FacadeClient interface {
	Configure(ctx context.Context, in *Config, opts ...grpc.CallOption) (*Status, error)
	Display(ctx context.Context, opts ...grpc.CallOption) (Facade_DisplayClient, error)
	Query(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error)
}

type facadeClient struct {
	cc *grpc.ClientConn
}

func NewFacadeClient(cc *grpc.ClientConn) FacadeClient {
	return &facadeClient{cc}
}

func (c *facadeClient) Configure(ctx context.Context, in *Config, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/facade.Facade/Configure", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facadeClient) Display(ctx context.Context, opts ...grpc.CallOption) (Facade_DisplayClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Facade_serviceDesc.Streams[0], "/facade.Facade/Display", opts...)
	if err != nil {
		return nil, err
	}
	x := &facadeDisplayClient{stream}
	return x, nil
}

type Facade_DisplayClient interface {
	Send(*RawText) error
	CloseAndRecv() (*Status, error)
	grpc.ClientStream
}

type facadeDisplayClient struct {
	grpc.ClientStream
}

func (x *facadeDisplayClient) Send(m *RawText) error {
	return x.ClientStream.SendMsg(m)
}

func (x *facadeDisplayClient) CloseAndRecv() (*Status, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Status)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *facadeClient) Query(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/facade.Facade/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FacadeServer is the server API for Facade service.
type FacadeServer interface {
	Configure(context.Context, *Config) (*Status, error)
	Display(Facade_DisplayServer) error
	Query(context.Context, *Empty) (*Status, error)
}

// UnimplementedFacadeServer can be embedded to have forward compatible implementations.
type UnimplementedFacadeServer struct {
}

func (*UnimplementedFacadeServer) Configure(ctx context.Context, req *Config) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Configure not implemented")
}
func (*UnimplementedFacadeServer) Display(srv Facade_DisplayServer) error {
	return status.Errorf(codes.Unimplemented, "method Display not implemented")
}
func (*UnimplementedFacadeServer) Query(ctx context.Context, req *Empty) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}

func RegisterFacadeServer(s *grpc.Server, srv FacadeServer) {
	s.RegisterService(&_Facade_serviceDesc, srv)
}

func _Facade_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Config)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacadeServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/facade.Facade/Configure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacadeServer).Configure(ctx, req.(*Config))
	}
	return interceptor(ctx, in, info, handler)
}

func _Facade_Display_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FacadeServer).Display(&facadeDisplayServer{stream})
}

type Facade_DisplayServer interface {
	SendAndClose(*Status) error
	Recv() (*RawText, error)
	grpc.ServerStream
}

type facadeDisplayServer struct {
	grpc.ServerStream
}

func (x *facadeDisplayServer) SendAndClose(m *Status) error {
	return x.ServerStream.SendMsg(m)
}

func (x *facadeDisplayServer) Recv() (*RawText, error) {
	m := new(RawText)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Facade_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacadeServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/facade.Facade/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacadeServer).Query(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Facade_serviceDesc = grpc.ServiceDesc{
	ServiceName: "facade.Facade",
	HandlerType: (*FacadeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Configure",
			Handler:    _Facade_Configure_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _Facade_Query_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Display",
			Handler:       _Facade_Display_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "facade.proto",
}
