// Code generated by protoc-gen-go. DO NOT EDIT.
// source: facade.proto

package facade

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

func init() { proto.RegisterFile("facade.proto", fileDescriptor_facade_992be187807cbe45) }

var fileDescriptor_facade_992be187807cbe45 = []byte{
	// 38 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x4b, 0x4c, 0x4e,
	0x4c, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x07, 0x04, 0x00, 0x00, 0xff, 0xff, 0x98, 0xdd,
	0x73, 0xe3, 0x0e, 0x00, 0x00, 0x00,
}
